### ISSUE TITLE
Prepare and check release

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gpkg12-nsg#1]
Prepare and check release 
Review that code builds properly 
Review that  core tests is properly imported when executing test
Review documentation

**Comment by lgoltz** [comment]
Fixed name of the suite (start of a test run failed before test data could be passed): https://github.com/opengeospatial/ets-gpkg12-nsg/commit/1aaef67a7264f935453cacf922f548ad3070e99d

Set version to 0.1-SNAPSHOT, organisation, status,...: https://github.com/opengeospatial/ets-gpkg12-nsg/commit/b45aa02e4450c8f6a9d7c06ae99b5fa3c1899d68

**Comment by lgoltz** [comment]
In the (README)[https://github.com/opengeospatial/ets-gpkg12-nsg/blob/master/README.md]  as well as the referenced specification (https://nsgreg.nga.mil/doc/view?i=4462&month=1&day=24&year=2018) the NSG standard base on GeoPackage 1.1 (I cannot find a hint to GeoPackage 1.2).
Do I overlook something or is this correct? 

I am wondering if the name of the repository is correct. I think it is fine to extend ets-gpkg12 as this test suite also tests GeoPackage 1.1 and 1.0, but it is confusing. Maybe it should be ets-gpkg11-nsg or ets-gpkg-nsg21 to avoid the version of the underlying specification?
