### ISSUE TITLE
N S G_ Tile Size Tests	 javax.imageio.IIOException: Can't create cache file!

### ISSUE THREAD

**Issue by chuck1987** [opengeospatial/ets-gpkg12-nsg#13]
I have attempted the Raster NSG profile test multiple times, with different file formats (JPEG/PNG) and I keep getting the same error in the title. I am able to properly read both my created geopackages from our internal software (using ImageIO), but your software test fails with this error. More than likely related to disk space issues, or permission issues.  I cannot attach any files since the file size is too large.

**Comment by dstenger** [comment]
Thank you for reporting.

What environment did you use for testing (e.g. beta, Docker)?
Can you provide some logging?

**Comment by chuck1987** [comment]
It was on the beta site.

The only logging I have is what appeared in the title. I did not run the 
test locally.

**Comment by chuck1987** [comment]
The geopackage in question can be downloaded from here :


https://hawk.compusult.net/ogc/sentinel2a_peurto_rico_tci.gpkg

**Comment by dstenger** [comment]
Thank you!

@keshav-nangare 
Can you do further investigation?

**Comment by keshav-nangare** [comment]
@dstenger 

I have tested ets locally but the Tile tests are successfully executed.

Here are the logs: [s0433.zip](https://github.com/opengeospatial/ets-gpkg12-nsg/files/1932185/s0433.zip)

[gpkg12_nsg_result_screenshot](https://user-images.githubusercontent.com/14732650/39052340-4b7f876a-44c9-11e8-8f63-65386287df3e.png)

**Comment by dstenger** [comment]
@chuck1987 Are you still having problems validating the GeoPackage?
If this is not the case, we can close this issue.

**Comment by dstenger** [comment]
Please reopen this issue if there are still any open questions.
