### ISSUE TITLE
Remove duplicated test inherited from ets-gpkg12

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-gpkg12-nsg#28]
E.g. test "tile Matrix Dimension Agreement"

**Comment by lgoltz** [comment]
PR #29, number of test was decreased from 49 to 15.

**Comment by dstenger** [comment]
# Functional test of fix

Setup [Docker environment](https://github.com/opengeospatial/teamengine-docker) with current versions of master branches (ets-gpkg12 and ets-gpkg12-nsg).

Execute test with ```GeoPackage_Vector_Rigel```.

Test ```tile Matrix Dimension Agreement``` is not executed in conformance class ```NSG```.
