### ISSUE TITLE
Test dataValidity_gpkg_contents fails with "ResultSet closed"

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-gpkg12-nsg#31]
PR #29 must be merged, can be tested with GeoPackage_Vector_Rigel.

**Comment by dstenger** [comment]
# Functional test of fix

Setup [Docker environment](https://github.com/opengeospatial/teamengine-docker) with current versions of master branches (ets-gpkg12 and ets-gpkg12-nsg).

Execute test with ```GeoPackage_Vector_Rigel```.

Test ```data Validity_gpkg_contents``` is passed successfully.
