### ISSUE TITLE
Geopackage having no Tile data results in SQLITE ERROR

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/ets-gpkg12-nsg#37]
Geopackage having no tile data, reports SQLITE_ERROR no such table gpkg_tile_matrix_set and another one for no such table gpkg_tile_matrix table.  

It should be okay to have a geopackage that has no tile data and if these tables are missing the tile tests should be skipped.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by ajanett** [comment]
I will fix this if needed.

**Comment by ajanett** [comment]
Several of the test geopackages within ets-gpkg12 are 'vector-only' data and should suffice for testing.

**Comment by lgoltz** [comment]
With PR https://github.com/opengeospatial/ets-gpkg12-nsg/pull/40 the test is successful not skipped, I think a SkipException should be thrown instead.

**Comment by ajanett** [comment]
Agreed. I've not employed the SkipException before but I do agree a Skip is more appropriate here than a pass.
