### ISSUE TITLE
Review list of implemented conformance classes in test report and documentation

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12-nsg#4]
Also review specification and check if all names of CCs are correct.

**Comment by lgoltz** [comment]
I cannot find any hints in https://nsgreg.nga.mil/doc/view?i=4379&month=1&day=24&year=2018 about additional required conformance class as in the base specification. So, I assume `Core` is the only basic conformance class (besides NSG).

Related discussion: https://github.com/opengeospatial/ets-gpkg12/issues/37

**Comment by dstenger** [comment]
Regarding basic conformance classes: This test suite should follow the results of https://github.com/opengeospatial/ets-gpkg12/issues/41.

**Comment by dstenger** [comment]
Changes were done accordingly to https://github.com/opengeospatial/ets-gpkg12/issues/37#issuecomment-367698436: https://github.com/opengeospatial/ets-gpkg12-nsg/commit/4eb2ba2e04877829582058ffbe780e87fdb7cf39

**Comment by dstenger** [comment]
PR was created: #5
