### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-gpkg12-nsg#50]
When running `mvn org.apache.maven.plugins:maven-dependency-plugin:analyze`, I get following warnings:
```
[WARNING] Used undeclared dependencies found:
[WARNING]    commons-io:commons-io:jar:1.3.2:compile
[WARNING]    org.hamcrest:hamcrest-core:jar:1.3:test
[WARNING]    org.opengis.cite.saxon:saxon9:jar:9.0.0.8:compile
[WARNING]    xml-apis:xml-apis:jar:1.4.01:compile
[WARNING]    com.beust:jcommander:jar:1.48:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.opengis.cite:geomatics-geotk:jar:1.15:compile
[WARNING]    javax.media:jai_core:jar:1.1.3:compile
[WARNING]    org.apache.commons:commons-io:jar:1.3.2:compile
[WARNING]    com.google.inject:guice:jar:4.0:test
```
All used undeclared compile dependencies shall be declared in Maven pom file.
All unused declared dependencies shall be removed from Maven pom file.

**Comment by keshav-nangare** [comment]
I have added used undeclared dependencies and removed unused declared dependencies except for the following dependencies.

1. `org.opengis.cite:geomatics-geotk` removal of this dependency causes compilation failure.
2. `com.google.inject:guice` is inherited from the parent and unable to exclude it.

Please find changes in #51 PR.
